services:
  # Frontend React App - Express Server
  - type: web
    name: academie-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /
    
    envVars:
      - key: NODE_ENV
        value: production
      # URL du backend déployé
      - key: VITE_API_URL
        value: https://academie-back-1.onrender.com
